# Notebook to convert network data into NetworkRug friendly format
### Requirements:

In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
import datetime

In [19]:
colnames = ["time_interval", "id_1", "id_2", "class_id_1", "class_id_2"]

df_2011 = pd.read_csv(
    "thiers_2011.csv",
    sep="\t",
    header=None,
    names=colnames
)

# Convert seconds → HH:MM
df_2011["hh_mm"] = df_2011["time_interval"].apply(
    lambda x: str(datetime.timedelta(seconds=int(x)))  # remove :ss
)

print("2011 interactions:")
display(df_2011)
print()


df_2012 = pd.read_csv(
    "thiers_2012.csv",
    sep="\t",
    header=None,
    names=colnames
)


# Convert to datetime (UTC)
df_2012["datetime_utc"] = pd.to_datetime(df_2012["time_interval"], unit="s", utc=True)

print("2012 interactions:")
display(df_2012)

2011 interactions:

       time_interval  id_1  id_2 class_id_1 class_id_2             hh_mm
0              54120    26    66         PC         PC          15:02:00
1              54140    26    66         PC         PC          15:02:20
2              54160    24    25         PC         PC          15:02:40
3              54160   100    37         PC         PC          15:02:40
4              54180    37    57         PC        PC*          15:03:00
...              ...   ...   ...        ...        ...               ...
28556         326130    81    75         PC         PC  3 days, 18:35:30
28557         326150    81    75         PC         PC  3 days, 18:35:50
28558         326210    81    75         PC         PC  3 days, 18:36:50
28559         326270    88   125         PC         PC  3 days, 18:37:50
28560         326450    56   125         PC         PC  3 days, 18:40:50

[28561 rows x 6 columns]

2012 interactions:

,time_interval,id_1,id_2,class_id_1,class_id_2,datetime_utc
0,1353303380,1170,1644,MP*1,MP*1,2012-11-19 05:36:20+00:00
1,1353303400,1170,1613,MP*1,MP*1,2012-11-19 05:36:40+00:00
2,1353303640,1170,1644,MP*1,MP*1,2012-11-19 05:40:40+00:00
3,1353303760,1181,1651,MP*1,MP*1,2012-11-19 05:42:40+00:00
4,1353303840,1108,1190,MP*1,MP*1,2012-11-19 05:44:00+00:00
...,...,...,...,...,...,...
45042,1354032580,880,887,PC*,PC*,2012-11-27 16:09:40+00:00
45043,1354032580,854,869,PSI*,PSI*,2012-11-27 16:09:40+00:00
45044,1354032600,880,887,PC*,PC*,2012-11-27 16:10:00+00:00
45045,1354032760,620,669,MP*2,MP*2,2012-11-27 16:12:40+00:00
45046,1354032880,669,677,MP*2,MP*2,2012-11-27 16:14:40+00:00

**time_interval 2011**
- no clear date, if converted into hh_mm format first entry is at 15:02

**time_interval 2012 could be in Unixcode**
- 2012-11-23 07:50:40 - 1353657040 seconds since 1 Jan 1970 00:00:00 UTC

In [23]:
import importlib
import data_transformation

importlib.reload(data_transformation)

In [24]:
from data_transformation import network_data_to_json

In [26]:
network_data_to_json(
    df_2012,
    "../data/contact_pattern_2012.json"
)